beforeTasks:
  image: node:12
  command:
    - "yarn --ignore-engines --network-timeout 100000"

tasks:
  - name: app
    image: node:12
    command: "yarn start"
  - name: lint
    image: node:12
    command: "yarn lint"
